{
 "title": "Twitter Statistics",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "TZ", "label": "Time Zone", "query": "UTC, +08:00" },
   { "name": "TREND", "label": "Trend days", "query": "7, 14, 30" }
  ]
 },
 "panels": [
  { "title": "Stat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Followers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  updated_at AS \"time\",\n  follower_count\nFROM stats\nWHERE\n  $__timeFilter(updated_at)\nORDER BY updated_at"
    }
   ]
  },
  {
   "title": "Tweets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  updated_at AS \"time\",\n  tweet_count\nFROM stats\nWHERE\n  $__timeFilter(updated_at)\nORDER BY updated_at"
    }
   ]
  },
  {
   "title": "Followers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  updated_at AS \"time\",\n  follower_count\nFROM stats\nWHERE\n  $__timeFilter(updated_at)\nORDER BY updated_at"
    }
   ]
  },
  {
   "title": "Users",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  CASE \n    WHEN is_follower=TRUE AND is_following=TRUE THEN 'friend'\n    WHEN is_follower=TRUE AND is_following=FALSE THEN 'follower'\n    WHEN is_follower=FALSE AND is_following=TRUE THEN 'following'\n    ELSE 'unkown' \n  END,\n  count(*)\nFROM users\nGROUP BY CASE \n    WHEN is_follower=TRUE AND is_following=TRUE THEN 'friend'\n    WHEN is_follower=TRUE AND is_following=FALSE THEN 'follower'\n    WHEN is_follower=FALSE AND is_following=TRUE THEN 'following'\n    ELSE 'unkown' \n  END\n\n\n\n\n"
    }
   ]
  },
  {
   "title": "Friend / Follower",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  CASE \n    WHEN is_following=TRUE THEN 'Friend'\n    WHEN is_following=FALSE THEN 'Follower'\n  END,\n  count(*)\nFROM users\nWHERE is_follower = TRUE\nGROUP BY CASE \n    WHEN is_following=TRUE THEN 'Friend'\n    WHEN is_following=FALSE THEN 'Follower'\n  END\n\n\n\n\n"
    }
   ]
  },
  {
   "title": "Friend / Following",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  CASE \n    WHEN is_follower=TRUE THEN 'Friend'\n    WHEN is_follower=FALSE THEN 'Following'\n  END,\n  count(*)\nFROM users\nWHERE is_following = TRUE\nGROUP BY CASE \n    WHEN is_follower=TRUE THEN 'Friend'\n    WHEN is_follower=FALSE THEN 'Following'\n  END\n\n\n\n\n"
    }
   ]
  },
  {
   "title": "Following",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  updated_at AS \"time\",\n  following_count\nFROM stats\nWHERE\n  $__timeFilter(updated_at)\nORDER BY updated_at"
    }
   ]
  },
  {
   "title": "Listed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  updated_at AS \"time\",\n  listed_count\nFROM stats\nWHERE\n  $__timeFilter(updated_at)\nORDER BY updated_at"
    }
   ]
  },
  {
   "title": "Activity (by selected Interval)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "New Follower",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM events\nWHERE\n  $__timeFilter(created_at) AND event = 'new_follower'"
    }
   ]
  },
  {
   "title": "Lost Follower",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM events\nWHERE\n  $__timeFilter(created_at) AND event = 'lost_follower'"
    }
   ]
  },
  {
   "title": "Cancel Following",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM events\nWHERE\n  $__timeFilter(created_at) AND event = 'cancel_following'"
    }
   ]
  },
  {
   "title": "New Following",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM events\nWHERE\n  $__timeFilter(created_at) AND event = 'new_following'"
    }
   ]
  },
  {
   "title": "Follower Increased",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  MAX(follower_count) - MIN(follower_count)\nFROM stats\nWHERE\n  $__timeFilter(updated_at)"
    }
   ]
  },
  {
   "title": "Following Increased",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  MAX(following_count) - MIN(following_count)\nFROM stats\nWHERE\n  $__timeFilter(updated_at)"
    }
   ]
  },
  {
   "title": "Tweets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  MAX(tweet_count) - MIN(tweet_count)\nFROM stats\nWHERE\n  $__timeFilter(updated_at)"
    }
   ]
  },
  {
   "title": "Listed Increased",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  MAX(listed_count) - MIN(listed_count)\nFROM stats\nWHERE\n  $__timeFilter(updated_at)"
    }
   ]
  },
  {
   "title": "New followers",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  u.profile_image as profile,\n  CONCAT(u.name, ' (', u.user_name, ')') as name,\n  u.user_name,\n  u.follower_count as follower, \n  u.tweet_count as tweet,\n  u.listed_count as listed,\n  u.last_active as 'last tweet'\nFROM events e\nJOIN users u ON u.id = e.user_id\nWHERE e.event='new_follower' AND u.is_follower = true AND $__timeFilter(e.created_at)\nORDER BY created_at desc\nLIMIT 500"
    }
   ]
  },
  {
   "title": "Lost followers",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  u.profile_image as profile,\n  CONCAT(u.name, ' (', u.user_name, ')') as name,\n  u.user_name,\n  u.follower_count as follower, \n  u.tweet_count as tweet,\n  u.listed_count as listed\nFROM events e\nJOIN users u ON u.id = e.user_id\nWHERE e.event='lost_follower' AND u.is_follower = false AND $__timeFilter(created_at)\nORDER BY created_at desc\nLIMIT 500"
    }
   ]
  },
  {
   "title": "New Following",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT\n  u.profile_image as profile,\n  CONCAT(u.name, ' (', u.user_name, ')') as name,\n  u.user_name,\n  u.follower_count as follower, \n  u.tweet_count as tweet,\n  u.listed_count as listed\nFROM events e\nJOIN users u ON u.id = e.user_id\nWHERE e.event='new_following' AND u.is_following = true AND $__timeFilter(created_at)\nORDER BY created_at desc\nLIMIT 500"
    }
   ]
  },
  {
   "title": "Cancel Following",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT\n  u.profile_image as profile,\n  CONCAT(u.name, ' (', u.user_name, ')') as name,\n  u.user_name,\n  u.follower_count as follower, \n  u.tweet_count as tweet,\n  u.listed_count as listed\nFROM events e\nJOIN users u ON u.id = e.user_id\nWHERE e.event='cancel_following' AND u.is_following = false AND $__timeFilter(created_at)\nORDER BY created_at desc\nLIMIT 500"
    }
   ]
  },
  {
   "title": "Trend ($TREND Days)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "repeat": "TREND",
   "collapsed": true,
   "panels": [
    {
     "title": "Daily Follower Increase/Decrease",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "targets": [
      {
       "rawSql": "SELECT\n  DATE(CONVERT_TZ(created_at, \"UTC\", \"$TZ\")) as \"time\",\n  COUNT(*) as count,\n  event as event\nFROM events\nWHERE (event='new_follower' OR event='lost_follower') AND CONVERT_TZ(created_at, \"UTC\", \"$TZ\") > DATE(CONVERT_TZ($__timeTo(), \"UTC\", \"$TZ\")) - INTERVAL $TREND DAY + INTERVAL 1 DAY\nGROUP BY DATE(CONVERT_TZ(created_at, \"UTC\", \"$TZ\")), event\nORDER BY DATE(CONVERT_TZ(created_at, \"UTC\", \"$TZ\"))"
      }
     ]
    },
    {
     "title": "Daily Tweet",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "targets": [
      {
       "rawSql": "SELECT s1.time as time, s1.tweet - s2.tweet as tweet FROM\n(SELECT DATE(CONVERT_TZ(updated_at, \"UTC\", \"$TZ\")) as time, MAX(tweet_count) as tweet FROM stats WHERE CONVERT_TZ(updated_at, \"UTC\", \"$TZ\") > DATE(CONVERT_TZ($__timeTo(), \"UTC\", \"$TZ\")) - INTERVAL $TREND DAY GROUP BY time) s1\nJOIN\n(SELECT DATE(CONVERT_TZ(updated_at, \"UTC\", \"$TZ\")) as time, MAX(tweet_count) as tweet FROM stats WHERE CONVERT_TZ(updated_at, \"UTC\", \"$TZ\") > DATE(CONVERT_TZ($__timeTo(), \"UTC\", \"$TZ\")) - INTERVAL $TREND DAY - INTERVAL 1 DAY GROUP BY time) s2\nON s1.time = s2.time + INTERVAL 1 DAY\n\n"
      }
     ]
    }
   ]
  },
  {
   "title": "User",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "All Followers",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
     "targets": [
      {
       "rawSql": "SELECT\n  profile_image as profile, CONCAT(name, ' (', user_name, ')') as name, user_name, follower_count as follower, following_count as following, tweet_count as tweet, last_active as 'last tweet', updated_at as 'update time'\nFROM users\nWHERE is_follower=true\nORDER BY follower_count DESC"
      }
     ]
    },
    {
     "title": "All Following",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 42 },
     "targets": [
      {
       "rawSql": "SELECT\n  profile_image as profile, CONCAT(name, ' (', user_name, ')') as name, user_name, follower_count as follower, following_count as following, tweet_count as tweet, last_active as 'last tweet', updated_at as 'update time'\nFROM users\nWHERE is_following=true\nORDER BY follower_count DESC"
      }
     ]
    },
    {
     "title": "Most Popular Friend",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
     "targets": [
      {
       "rawSql": "SELECT\n  profile_image as profile, CONCAT(name, ' (', user_name, ')') as name, user_name, follower_count\nFROM users\nWHERE\n  is_follower = TRUE AND is_following = TRUE\nORDER BY follower_count desc\nlimit 100"
      }
     ]
    },
    {
     "title": "Recommend to follow",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
     "targets": [
      {
       "rawSql": "\nSELECT\n  profile_image as profile, CONCAT(name, ' (', user_name, ')') as name, user_name, follower_count as follower, tweet_count as tweet, last_active as 'last tweet'\nFROM users\nWHERE\n  is_following = FALSE AND is_follower = TRUE AND last_active = (SELECT MAX(last_active) FROM users) AND follower_count > (SELECT AVG(follower_count) FROM users WHERE is_follower=TRUE)\nORDER BY follower_count/(tweet_count+1)/(tweet_count+1) desc\nlimit 20"
      }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Logs",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "rawSql": "SELECT\n  created_at AS \"time\",\n  level, message\nFROM logs\nWHERE\n  $__timeFilter(created_at)\nORDER BY created_at desc limit 50"
      }
     ]
    },
    {
     "title": "System Variables",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "targets": [
      { "rawSql": "SELECT\n  *\nFROM sys" }
     ]
    },
    {
     "title": "Scraper Duration",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "rawSql": "SELECT\n  started_at AS \"time\",\n  completed_at - started_at as duration\nFROM iterations\nWHERE\n  $__timeFilter(started_at)\nORDER BY started_at"
      }
     ]
    }
   ]
  }
 ]
}